language: scala
cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt/boot"
scala:
  - 2.11.6
jdk:
  - oraclejdk8
  - openjdk7
script:
  - sbt clean coverage test package
#  - if [ "$TRAVIS_BRANCH" == "release" ]; then sbt publish; fi
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
# after_success: "sbt coveralls"
# before_deploy:
#   - ./.before-deploy.sh
branches:
  except:
    - /^v([0-9]+(?:\.[0-9]+){0,2})/
