language: scala
cache:
  directories:
    - "$HOME/.ivy2"
    - "$HOME/.sbt"
scala:
  - 2.11.2
  - 2.11.6
jdk:
  - oraclejdk8
  - openjdk7
script: "sbt clean coverage test"
after_success: "sbt coveralls"
